export const SET_NAME = 'SET_NAME';
//shipper related
export const SET_SHIPPER_DETAILS_REQUEST = 'SET_SHIPPER_DETAILS_REQUEST';
export const SET_SHIPPER_DETAILS = 'SET_SHIPPER_DETAILS';
export const SET_SHIPPER_ID = 'SET_SHIPPER_ID';
export const SET_SHIPPER_DETAILS_COMPLETED = 'SET_SHIPPER_DETAILS_COMPLETED';
export const SET_SHIPPER_REQUEST_QUOTES_DETAILS = 'SET_SHIPPER_REQUEST_QUOTES_DETAILS';

// error related
export const ERROR_GENERATED = 'ERROR_GENERATED';
export const SET_ERROR = 'SET_ERROR';
export const HIDE_ERROR = 'HIDE_ERROR';

//carrier related
export const SET_CARRIER_DETAILS_REQUEST = 'SET_CARRIER_DETAILS_REQUEST';
export const SET_CARRIER_DETAILS = 'SET_CARRIER_DETAILS';
export const SET_CARRIER_ID = 'SET_CARRIER_ID';
export const SET_CARRIER_DETAILS_COMPLETED = 'SET_CARRIER_DETAILS_COMPLETED';

//loadfactor related
export const SET_LOADFACTOR_USER_ID = 'SET_LOADFACTOR_USER_ID';

//Admin related
export const SET_ADMIN_USER_ID = 'SET_ADMIN_USER_ID';